version: '3.7'
services:
  app:
    container_name: wongkito
    image: wongkito
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: wongkito_database
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - backend


volumes:
  pkg:
    driver: local
  my-db:
    driver: local

networks:
  backend:
    driver: bridge